export const AppRoutesConfig = {
  routeNames: {
    home: '',
    about: 'about',
    contact: 'contact',
    generator: 'generator',
    map: 'map',
    trips: 'trips',
    profile: 'profile',
    settings: 'settings',
    login: 'login',
    register: 'register',
    notFound: '**',
  },
  routes: {
    home: '',
    about: '/about',
    contact: '/contact',
    generator: '/generator',
    map: '/map',
    trips: '/trips',
    profile: '/profile',
    settings: '/settings',
    login: '/login',
    register: '/register',
    notFound: '/404',
  },
};
